#!/usr/bin/ruby
#
# This file is part of CPEE-WORKLIST
#
# CPEE-WORKLIST is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# CPEE-WORKLIST is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with CPEE-WORKLIST (file LICENSE in the main directory). If not, see
# <http://www.gnu.org/licenses/>.

require 'rubygems'
if File.exist? File.join(__dir__,'../lib/cpee-worklist/implementation.rb')
  require_relative '../lib/cpee-worklist/implementation'
else
  require 'cpee-worklist/implementation'
end

options = {
  :host => 'localhost',
  :port => 9398,
  :secure => false
}

Riddl::Server.new(CPEE::Worklist::SERVER, options) do |opts|
  accessible_description true
  cross_site_xhr true

  use CPEE::Worklist::implementation(opts)
end.loop!
