#!/usr/bin/ruby
curpath = __dir__
require 'rubygems'
require 'optparse'
require 'fileutils'
require 'typhoeus'
require 'zip'
require 'xml/smart'

def wrap(s, width=78, indent=18)
	lines = []
	line, s = s[0..indent-2], s[indent..-1]
  s.split(/\n/).each do |ss|
    ss.split(/[ \t]+/).each do |word|
      if line.size + word.size >= width
        lines << line
        line = (" " * (indent)) + word
      else
        line << " " << word
      end
    end
    lines << line if line
    line = (" " * (indent-1))
  end
	return lines.join "\n"
end

def js_libs(cockpit)
  res = Typhoeus.get('https://cpee.org/js_libs/js_libs.zip')
  if res.success?
    File.write(File.join(cockpit,'js_libs.zip'),res.response_body)
    Zip::File.open(File.join(cockpit,'js_libs.zip')) do |zip_file|
      zip_file.each do |entry|
        case entry.ftype
          when :directory
            Dir.mkdir(File.join(cockpit,entry.name)) rescue nil
          when :file
            File.write(File.join(cockpit,entry.name),entry.get_input_stream.read)
          when :symlink
            FileUtils.ln_s(File.join('.',entry.get_input_stream.read),File.join(cockpit,entry.name), force: true)
        end
      end
    end
    true
  else
    puts 'Internet access required to download javascript libs from "http://cpee.org/js_libs/js_libs.zip".'
    false
  end
end

ARGV.options { |opt|
  opt.summary_indent = ' ' * 2
  opt.summary_width = 15
  opt.banner = "Usage:\n#{opt.summary_indent}#{File.basename($0)} [options] cpui DIR | new DIR\n"
  opt.on("Options:")
  opt.on("--help", "-h", "This text") { puts opt; exit }
	opt.on("")
  opt.on(wrap("[cpui DIR]        scaffolds a sample html client. New versions might require manual merging if you changed something."))
	opt.on("")
  opt.on(wrap("[new DIR]         scaffolds a sample instantiation service. Post a testset to a model to keep going in one operation."))
	opt.on("")
  opt.on(wrap("[filter URL key]  return all tasks that match a certain filter criterion."))
	opt.on("")
  opt.on(wrap("[filter_a URL]    return all tasks that point to abandoned instances."))
	opt.on("")
  opt.on(wrap("[delete_a URL]    delete all tasks that point to abandoned instances."))
	opt.on("")
  opt.on(wrap("[delete_f URL]    delete all tasks that match a certain filter criterion."))
  opt.parse!
}

if (ARGV.length <  2) ||
   (ARGV.length == 2  && !(%w(cpui new filter_a delete_a).include?(ARGV[0]))) ||
   (ARGV.length == 3  && !(%w(filter delete_f).include?(ARGV[0]))) ||
   (ARGV.length >  3)
  puts ARGV.options
  exit
end
command = ARGV[0]
p1      = ARGV[1]

if command == 'new'
  insta = "#{curpath}/../server/"
  FileUtils.mkdir(p1) rescue nil
  if !File.exist?(p1)
    FileUtils.cp_r(insta,p1)
  else
    FileUtils.cp_r(Dir.glob(File.join(insta,'*')).delete_if{|e| e =~ /\.conf/ },p1,remove_destination: true)
    puts 'Directory already exists, updating ...'
  end
elsif command == 'filter'
  if p1 !~ /^http/ || ARGV[2] !~ /^\w+=/
    puts ARGV.options
    exit
  end
  res = Typhoeus.get(File.join(p1,'/'))
  pname, pkey = ARGV[2].split('=',2)
  if res.success?
    doc = XML::Smart.string(res.body)
    doc.find("/tasks/task[@#{pname}=\"#{pkey}\"]").each do |ele|
      puts "#{ele.attributes['callback_id']}; #{ele.attributes['cpee_label']};  #{ele.attributes['cpee_instance']}"
    end
  end
elsif command == 'filter_a'
  if p1 !~ /^http/
    puts ARGV.options
    exit
  end
  res = Typhoeus.get(File.join(p1,'/'))
  if res.success?
    doc = XML::Smart.string(res.body)
    doc.find("/tasks/task").each do |ele|
      res = Typhoeus.get(File.join(ele.attributes['cpee_base'],ele.attributes['cpee_instance'],'properties','attributes','uuid','/'))
      if res.success?
        if res.body != ele.attributes['instance_uuid']
          puts "#{ele.attributes['callback_id']}; #{ele.attributes['cpee_label']};  #{ele.attributes['cpee_instance']}"
        else
          ### TODO check if abandoned or finished to catch the rest of the the mischiefous tasks
        end
      else
        puts "#{ele.attributes['callback_id']}; #{ele.attributes['cpee_label']};  #{ele.attributes['cpee_instance']}"
      end
    end
  end
elsif command == 'delete_a'
  if p1 !~ /^http/
    puts ARGV.options
    exit
  end
  wl = File.join(p1,'/')
  res = Typhoeus.get(wl)
  if res.success?
    doc = XML::Smart.string(res.body)
    doc.find("/tasks/task").each do |ele|
      res = Typhoeus.get(File.join(ele.attributes['cpee_base'],ele.attributes['cpee_instance'],'properties','attributes','uuid','/'))
      if res.success?
        if res.body != ele.attributes['instance_uuid']
          Typhoeus.delete File.join(wl,'tasks',ele.attributes['callback_id'])
        else
          ### TODO check if abandoned or finished to catch the rest of the the mischiefous tasks
        end
      else
        Typhoeus.delete File.join(wl,'tasks',ele.attributes['callback_id'])
      end
    end
  end
elsif command == 'cpui'
  insta = "#{curpath}/../ui/"
  if !File.exist?(p1)
    FileUtils.cp_r(insta,p1)
  else
    FileUtils.cp_r(Dir.glob(File.join(insta,'*')),p1,remove_destination: true)
    puts "Directory already exists, updating ..."
  end
  js_libs(p1)
end
